import { userAgent } from 'next/server';
import { itineraryAPI } from './organizer/trip/itinerary';
import { m } from 'framer-motion';

export const TAGS = {
  dayDescriptions: 'dayDescriptions',
  faqs: 'faqs',
  transits: 'transits',
  users: 'users',
  admins: 'admins',
  organizations: 'organizations',
  orgs: 'org',
  trip:'trip',
  itinerary: 'itinerary',
  itineraryDayDetails: 'itineraryDayDetails',
  dayDescription: 'dayDescription',
  transit: 'transit',
  stay: 'stay',
  meal: 'meal',
  activity: 'activity',
  exclusion: 'exclusion',
  faq: 'faq',
  pricing: 'pricing',
  review: 'review',
  user: 'user',
  otp: 'otp',
  notifications: 'notifications',
  travelerProfile: 'travelerProfile',
  tripLibraryGroupLeader: 'TripLibraryGroupLeader',
  organizerProfile: 'organizerProfile',
  tripLibraryMeal: 'tripLibraryMeal',
  tripLibraryStay: 'tripLibraryStay',
  tripLibraryActivity: 'tripLibraryActivity',
  tripLeads: 'tripLeads',
  tickets: "tickets",
} as const;