export const TRIP_DETAILS = {
    PAGE: {
        LOADING: "Loading trip…",
        ERROR: "Failed to load trip",
        NOT_FOUND: "Trip not found",
        DEFAULT_LOGO: "Trip Details",
        REPORT_BUTTON: "Report this trip",
        DAY_PREFIX: "Day ",
    },
    HERO: {
        DEFAULT_TITLE: "Trip",
    },
    HEADER: {
        TRIP_TITLE_DEFAULT: "Trip Title",
        PROVIDER_DEFAULT: "Organizer",
        ORGANIZER_DEFAULT: "Trip Leader",
        MORE_DETAILS: "More Details",
        VIEW_PROFILE: "View Profile",
    },
    HIGHLIGHTS: {
        TITLE: "Trip Highlights",
        EMPTY: "No highlights added yet.",
    },
    ITINERARY: {
        TITLE: "Day Wise Itinerary",
        VIEW_FULL: "View Full Itinerary",
        ACTIVITY_DEFAULT_NAME: "Activity",
        EMPTY_DAY: "No activities added for this day.",
    },
    INCLUDED: {
        TABS: ["Transfers", "Meals", "Stays", "Activities"],
        EMPTY: "No items added yet.",
        INCLUDED_LABEL: "Included",
    },
    EXCLUDED: {
        TITLE: "What's Excluded",
        EMPTY: "No exclusions added.",
    },
    FAQ: {
        TITLE: "FAQ",
        EMPTY: "No FAQs available.",
    },
    SIDEBAR: {
        STARTING_FROM: "Starting from",
        PER_PERSON: "per person",
        OFF: "OFF",
        ORIGINAL: "original",
        BASE_PACKAGE_TITLE: "Base Package",
        STANDARD_PACKAGE: "Standard Package",
        STANDARD_DESC: "Includes all base benefits",
        SELECT_OPTION_WARNING: "Please select an option to proceed",
        REQUEST_INVITE: "Request Invite",
        SEND_QUERY: "Send Query",
        SHARE_TRIP: "Share Trip",
    },
    MOBILE_BAR: {
        STARTING_FROM: "Starting from",
        OFF: "OFF",
        ORIGINAL: "original",
        VIEW_OPTIONS: "View Options",
    },
    PRICING_MODAL: {
        TITLE: "Pricing Options",
        BASE_PACKAGE: "Base Package",
        STANDARD_PRICING: "Standard trip package pricing",
        OFF: "OFF",
        WARNING: "Prices may change based on availability",
        REQUEST_INVITE: "Request Invite",
    },
    PRICING_DETAILS_MODAL: {
        TITLE: "Pricing Details",
        EMI_AVAILABLE: "EMI Options Available",
        CANCELLATION_POLICY: "Cancellation Policy",
        POLICY_30_DAYS: "• 30+ days: 80% refund",
        POLICY_15_DAYS: "• 15–29 days: 50% refund",
        POLICY_7_DAYS: "• 7–14 days: 25% refund",
        POLICY_LESS_7: "• Less than 7 days: No refund",
        CANCEL: "Cancel",
        REQUEST_INVITE: "Request Invite",
    },
    LEADER_MODAL: {
        DEFAULT_NAME: "Trip Leader",
        DEFAULT_BIO: "Hi, I'm an experienced trip leader.",
        DEFAULT_TAGLINE: "Trip Leader",
        LIKES_TEXT: "If you're seeking memorable trips",
        LIKES_SUFFIX: "likes",
        FULL_BIO_TITLE: "FULL BIOGRAPHY",
        YEARS_EXP: "Years Experience",
        TRIPS_ORG: "Trips Organized",
        HAPPY_TRAVELERS: "Happy Travelers",
        CLOSE: "Close",
    },
    REPORT_MODAL: {
        TITLE: "Report this trip",
        DESC: "Please let us know why you are reporting this trip.",
        SUBMIT: "Submit Report",
        CANCEL: "Cancel",
    },
    ASK_MODAL: {
        TITLE: "Ask a Question",
        DESC: "Send your query to the organizer.",
        SUBMIT: "Send Message",
        CANCEL: "Cancel",
    },
    INFO_CARDS: {
        ROUTE: "Route",
        DATES: "Dates",
        DURATION: "Duration",
        AGE_GROUP: "Age Group",
        GROUP_SIZE: "Group Size",
    },
};
