const durations = ["1-2 Days", "3-4 Days", "5-7 Days", "1-2 Weeks", "2+ Weeks"];
const ageGroups = ["All Ages", "18-25", "26-35", "36-45", "46-55", "55+"];
const moods = ["Adventure", "Relaxation", "Culture", "Foodie", "Sports"];
const regions = [
  "North India",
  "South India",
  "East India",
  "West India",
  "Islands",
];
const difficulties = ["Easy", "Medium", "Difficult", "Moderate"];
const cancellationTypes = ["Flexible", "Strict", "Moderate", "Non-Refundable"];

const mockTrips = [
  {
    id: 1,
    title: "Manali Adventure Trek",
    location: "Manali, Himachal Pradesh",
    startPoint: "Delhi",
    endPoint: "Manali",
    dates: "15-20 May 2024",
    price: 15000,
    originalPrice: 18000,
    rating: 4.5,
    reviewCount: 234,
    duration: "5 Days",
    coverImage: "/manali-mountains-trek.png",
    organizer: "Mountain Adventures",
    organizerLogo: "/mountain-logo.png",
    organizerRating: 4.8,
    moodTags: ["Adventure", "Culture"],
    region: "North India",
    ageGroup: "18-35",
    difficulty: "Medium",
    cancellation: "Flexible",
    emi: true,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["15% Early Bird", "Free Meals"],
    highlights: ["Rohtang Pass", "Solang Valley", "Local Culture"],
    tags: ["Mountains", "Trekking", "Photography"],
    groupSize: "8-12 people",
  },
  {
    id: 2,
    title: "Kerala Backwater Cruise",
    location: "Alleppey, Kerala",
    startPoint: "Kochi",
    endPoint: "Alleppey",
    dates: "22-25 May 2024",
    price: 12000,
    originalPrice: 15000,
    rating: 4.4,
    reviewCount: 189,
    duration: "3 Days",
    coverImage: "/kerala-backwaters.png",
    organizer: "South India Tours",
    organizerLogo: "/beach-logo.png",
    organizerRating: 4.6,
    moodTags: ["Relaxation", "Culture"],
    region: "South India",
    ageGroup: "All Ages",
    difficulty: "Easy",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["20% Off"],
    highlights: ["Houseboat Stay", "Traditional Cuisine", "Village Tours"],
    tags: ["Backwaters", "Houseboat", "Peaceful"],
    groupSize: "4-8 people",
  },
  {
    id: 3,
    title: "Rajasthan Royal Heritage",
    location: "Jaipur-Udaipur-Jodhpur",
    startPoint: "Delhi",
    endPoint: "Jodhpur",
    dates: "1-7 June 2024",
    price: 25000,
    originalPrice: 30000,
    rating: 4.8,
    reviewCount: 312,
    duration: "7 Days",
    coverImage: "/rajasthan-palace.png",
    organizer: "Heritage Travels",
    organizerLogo: "/heritage-logo.png",
    organizerRating: 4.9,
    moodTags: ["Culture", "Luxury"],
    region: "North India",
    ageGroup: "26-55",
    difficulty: "Easy",
    cancellation: "Strict",
    emi: true,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Palace Stay Included"],
    highlights: ["Royal Palaces", "Desert Safari", "Cultural Shows"],
    tags: ["Heritage", "Palaces", "Desert"],
    groupSize: "10-15 people",
  },
  {
    id: 4,
    title: "Goa Beach Paradise",
    location: "North & South Goa",
    startPoint: "Mumbai",
    endPoint: "Goa",
    dates: "10-14 June 2024",
    price: 8000,
    originalPrice: 10000,
    rating: 4.3,
    reviewCount: 456,
    duration: "4 Days",
    coverImage: "/goa-beach-sunset.png",
    organizer: "Coastal Adventures",
    organizerLogo: "/beach-logo.png",
    organizerRating: 4.4,
    moodTags: ["Relaxation", "Adventure", "Nightlife"],
    region: "West India",
    ageGroup: "18-35",
    difficulty: "Easy",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Water Sports Free"],
    highlights: ["Beach Hopping", "Water Sports", "Nightlife"],
    tags: ["Beach", "Water Sports", "Party"],
    groupSize: "6-12 people",
  },
  {
    id: 5,
    title: "Ladakh Bike Expedition",
    location: "Leh-Ladakh",
    startPoint: "Delhi",
    endPoint: "Leh",
    dates: "20-30 June 2024",
    price: 35000,
    originalPrice: 40000,
    rating: 4.9,
    reviewCount: 167,
    duration: "10 Days",
    coverImage: "/ladakh-bike-adventure.png",
    organizer: "Himalayan Riders",
    organizerLogo: "/abstract-bike-logo.png",
    organizerRating: 4.8,
    moodTags: ["Adventure", "Extreme"],
    region: "North India",
    ageGroup: "21-45",
    difficulty: "Difficult",
    cancellation: "Strict",
    emi: true,
    onRequest: true,
    doubleOccupancy: false,
    deals: ["Bike Rental Included"],
    highlights: ["High Altitude Passes", "Monasteries", "Scenic Routes"],
    tags: ["Biking", "Mountains", "Adventure"],
    groupSize: "4-8 people",
  },
  {
    id: 6,
    title: "Darjeeling Tea Gardens",
    location: "Darjeeling, West Bengal",
    startPoint: "Kolkata",
    endPoint: "Darjeeling",
    dates: "5-9 July 2024",
    price: 9000,
    originalPrice: 11000,
    rating: 4.6,
    reviewCount: 203,
    duration: "4 Days",
    coverImage: "/darjeeling-tea-gardens.png",
    organizer: "Hill Station Tours",
    organizerLogo: "/elegant-tea-logo.png",
    organizerRating: 4.7,
    moodTags: ["Relaxation", "Culture"],
    region: "East India",
    ageGroup: "All Ages",
    difficulty: "Easy",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Tea Tasting Included"],
    highlights: ["Sunrise at Tiger Hill", "Tea Garden Tours", "Toy Train Ride"],
    tags: ["Hills", "Tea Gardens", "Heritage"],
    groupSize: "6-10 people",
  },
  {
    id: 7,
    title: "Andaman Island Paradise",
    location: "Port Blair, Andaman",
    startPoint: "Chennai",
    endPoint: "Port Blair",
    dates: "15-22 July 2024",
    price: 22000,
    originalPrice: 26000,
    rating: 4.7,
    reviewCount: 145,
    duration: "7 Days",
    coverImage: "/andaman-beach-scene.png",
    organizer: "Island Adventures",
    organizerLogo: "/beach-logo.png",
    organizerRating: 4.5,
    moodTags: ["Relaxation", "Adventure"],
    region: "Islands",
    ageGroup: "18-50",
    difficulty: "Easy",
    cancellation: "Moderate",
    emi: true,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Scuba Diving Package"],
    highlights: ["Radhanagar Beach", "Scuba Diving", "Cellular Jail"],
    tags: ["Islands", "Beaches", "Water Sports"],
    groupSize: "8-12 people",
  },
  {
    id: 8,
    title: "Rishikesh Yoga Retreat",
    location: "Rishikesh, Uttarakhand",
    startPoint: "Delhi",
    endPoint: "Rishikesh",
    dates: "25-30 July 2024",
    price: 7000,
    originalPrice: 9000,
    rating: 4.8,
    reviewCount: 278,
    duration: "5 Days",
    coverImage: "/rishikesh-yoga-ganges.png",
    organizer: "Spiritual Journeys",
    organizerLogo: "/yoga-logo.png",
    organizerRating: 4.9,
    moodTags: ["Relaxation", "Spiritual"],
    region: "North India",
    ageGroup: "All Ages",
    difficulty: "Easy",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Meditation Sessions Free"],
    highlights: ["Daily Yoga Classes", "Ganga Aarti", "Adventure Sports"],
    tags: ["Yoga", "Spiritual", "River"],
    groupSize: "10-15 people",
  },
  {
    id: 9,
    title: "Hampi Heritage Walk",
    location: "Hampi, Karnataka",
    startPoint: "Bangalore",
    endPoint: "Hampi",
    dates: "5-8 August 2024",
    price: 6500,
    originalPrice: 8000,
    rating: 4.5,
    reviewCount: 156,
    duration: "3 Days",
    coverImage: "/hampi-ruins-temples.png",
    organizer: "Heritage Walks",
    organizerLogo: "/heritage-logo.png",
    organizerRating: 4.6,
    moodTags: ["Culture", "History"],
    region: "South India",
    ageGroup: "25-60",
    difficulty: "Moderate",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Guide Included"],
    highlights: ["Vijayanagara Ruins", "Stone Chariot", "Sunset Point"],
    tags: ["Heritage", "Temples", "History"],
    groupSize: "8-12 people",
  },
  {
    id: 10,
    title: "Spiti Valley Expedition",
    location: "Spiti Valley, Himachal Pradesh",
    startPoint: "Delhi",
    endPoint: "Kaza",
    dates: "15-25 August 2024",
    price: 28000,
    originalPrice: 32000,
    rating: 4.9,
    reviewCount: 89,
    duration: "10 Days",
    coverImage: "/spiti-valley-mountains.png",
    organizer: "High Altitude Tours",
    organizerLogo: "/mountain-logo.png",
    organizerRating: 4.8,
    moodTags: ["Adventure", "Extreme"],
    region: "North India",
    ageGroup: "21-50",
    difficulty: "Difficult",
    cancellation: "Strict",
    emi: true,
    onRequest: true,
    doubleOccupancy: false,
    deals: ["Oxygen Support Included"],
    highlights: ["Key Monastery", "Chandratal Lake", "High Altitude Desert"],
    tags: ["Mountains", "Desert", "Monasteries"],
    groupSize: "4-8 people",
  },
  {
    id: 11,
    title: "Mumbai Street Food Tour",
    location: "Mumbai, Maharashtra",
    startPoint: "Mumbai",
    endPoint: "Mumbai",
    dates: "1-3 September 2024",
    price: 4500,
    originalPrice: 5500,
    rating: 4.4,
    reviewCount: 324,
    duration: "2 Days",
    coverImage: "/mumbai-street-food.png",
    organizer: "Food Adventures",
    organizerLogo: "/diverse-food-logo.png",
    organizerRating: 4.3,
    moodTags: ["Culture", "Food"],
    region: "West India",
    ageGroup: "All Ages",
    difficulty: "Easy",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Food Tastings Included"],
    highlights: ["Street Food Tours", "Local Markets", "Cooking Classes"],
    tags: ["Food", "Culture", "City"],
    groupSize: "6-10 people",
  },
  {
    id: 12,
    title: "Coorg Coffee Plantation",
    location: "Coorg, Karnataka",
    startPoint: "Bangalore",
    endPoint: "Coorg",
    dates: "10-13 September 2024",
    price: 8500,
    originalPrice: 10000,
    rating: 4.6,
    reviewCount: 198,
    duration: "3 Days",
    coverImage: "/coorg-coffee-plantation.png",
    organizer: "Plantation Tours",
    organizerLogo: "/coffee-plantation-logo.png",
    organizerRating: 4.7,
    moodTags: ["Relaxation", "Nature"],
    region: "South India",
    ageGroup: "All Ages",
    difficulty: "Easy",
    cancellation: "Flexible",
    emi: false,
    onRequest: false,
    doubleOccupancy: true,
    deals: ["Coffee Tasting Free"],
    highlights: [
      "Coffee Plantation Tours",
      "Waterfall Visits",
      "Spice Gardens",
    ],
    tags: ["Coffee", "Nature", "Hills"],
    groupSize: "8-12 people",
  },
];

export { mockTrips, durations, ageGroups, moods, regions, difficulties, cancellationTypes };export const moodTags = [
    "Mountains",
    "Beach",
    "Forest and Wildlife",
    "Sky and Stargazing",
    "Heritage and Culture",
    "Camping",
    "Productivity and Creativity",
    "Women Only",
    "Spiritual and Wellness",
    "Party and Music",
    "Trekking",
    "Adventure",
    "Motorsports",
    "Weekender",
    "Solo Escape",
  ];

